### ISSUE TITLE
Deletion of selected rows chosen using CTRL or Shift key function

### ISSUE THREAD

**Issue by ToddVolkening** [agrc/electrofishing#115] opened 2018-04-03 16:50 UTC
Catch > Deletion of selected rows chosen using CTRL or Shift key function. 

Refer to Scott Davis’s comments for #22 in Google Word Doc

Referenced as UDWR # 405

**Comment by stdavis** [comment] 2018-05-11 14:13
Duplicate of #87

**Closed by stdavis** 2018-05-11 14:13 UTC
