### ISSUE TITLE
Allow for one decimal point in pH field

### ISSUE THREAD

**Issue by ToddVolkening** [agrc/electrofishing#121] opened 2018-04-03 18:18 UTC
Habitat tab > pH field > Allow for one decimal point.  Have the values be to 1 decimal place with limit between 0 and 14. (e.g. 7.3 or 11.6)

Duplicate request as UDWR #404, but I have it as a separate line item, so I thought I'd include anyway.  

Previously referenced as #62 and #31 in Google Word Doc and as AGRC GitHub #60

Referenced as UDWR #411

**Comment by steveoh** [comment] 2018-04-04 00:57
closing as duplicate of #114

**Closed by steveoh** 2018-04-04 00:57 UTC
